apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx
  replicas: 3

# kubectl create -f rc-definition.yml
# kubectl get replicationcontroller
# kebuctl get pods # you will see 3 pods running now ~

# Kubernetes Controllers:
# - ReplicationController (one kind)

# Reason why we need replica controller / set:
# When application crashed or failed, we'd like to keep providing our services, eg:
# create a backup pod and make sure it will be able to run when other / or one of pods failed
# so app will continue to run on another back up pod !!! (Just use for backup !!!!!)


# ReplicationController is outdated, now we all use ReplicaSet !!!!
